//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceProyectoSoap")]
    public interface WebServiceProyectoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IniciarArbol", ReplyAction="*")]
        void IniciarArbol();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Proyecto.ServiceReference1.HelloWorldResponse HelloWorld(Proyecto.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pusuario1 del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetDatosJuego", ReplyAction="*")]
        Proyecto.ServiceReference1.SetDatosJuegoResponse SetDatosJuego(Proyecto.ServiceReference1.SetDatosJuegoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetUsuario1Result del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsuario1", ReplyAction="*")]
        Proyecto.ServiceReference1.GetUsuario1Response GetUsuario1(Proyecto.ServiceReference1.GetUsuario1Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetUsuario2Result del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsuario2", ReplyAction="*")]
        Proyecto.ServiceReference1.GetUsuario2Response GetUsuario2(Proyecto.ServiceReference1.GetUsuario2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNumeroNivel1", ReplyAction="*")]
        int GetNumeroNivel1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNumeroNivel2", ReplyAction="*")]
        int GetNumeroNivel2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNumeroNivel3", ReplyAction="*")]
        int GetNumeroNivel3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNumeroNivel4", ReplyAction="*")]
        int GetNumeroNivel4();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTamX", ReplyAction="*")]
        int GetTamX();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTamY", ReplyAction="*")]
        int GetTamY();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTipoJuego", ReplyAction="*")]
        int GetTipoJuego();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetTiempoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTiempo", ReplyAction="*")]
        Proyecto.ServiceReference1.GetTiempoResponse GetTiempo(Proyecto.ServiceReference1.GetTiempoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ruta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarJuegoActual", ReplyAction="*")]
        Proyecto.ServiceReference1.CargarJuegoActualResponse CargarJuegoActual(Proyecto.ServiceReference1.CargarJuegoActualRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ruta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarJuegos", ReplyAction="*")]
        Proyecto.ServiceReference1.CargarJuegosResponse CargarJuegos(Proyecto.ServiceReference1.CargarJuegosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ruta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarTablero", ReplyAction="*")]
        Proyecto.ServiceReference1.CargarTableroResponse CargarTablero(Proyecto.ServiceReference1.CargarTableroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ruta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarUsuarios", ReplyAction="*")]
        Proyecto.ServiceReference1.CargarUsuariosResponse CargarUsuarios(Proyecto.ServiceReference1.CargarUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pnickname del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarUsuario", ReplyAction="*")]
        Proyecto.ServiceReference1.BuscarUsuarioResponse BuscarUsuario(Proyecto.ServiceReference1.BuscarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Llamadaagraficar", ReplyAction="*")]
        Proyecto.ServiceReference1.LlamadaagraficarResponse Llamadaagraficar(Proyecto.ServiceReference1.LlamadaagraficarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pnickname del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Devolverusuario", ReplyAction="*")]
        Proyecto.ServiceReference1.DevolverusuarioResponse Devolverusuario(Proyecto.ServiceReference1.DevolverusuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pnickname del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarUsuarios", ReplyAction="*")]
        Proyecto.ServiceReference1.ModificarUsuariosResponse ModificarUsuarios(Proyecto.ServiceReference1.ModificarUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pnicknameantiguo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarNicknameUsuarios", ReplyAction="*")]
        Proyecto.ServiceReference1.ModificarNicknameUsuariosResponse ModificarNicknameUsuarios(Proyecto.ServiceReference1.ModificarNicknameUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pnickname del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuarios", ReplyAction="*")]
        Proyecto.ServiceReference1.EliminarUsuariosResponse EliminarUsuarios(Proyecto.ServiceReference1.EliminarUsuariosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Proyecto.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Proyecto.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDatosJuegoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDatosJuego", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.SetDatosJuegoRequestBody Body;
        
        public SetDatosJuegoRequest() {
        }
        
        public SetDatosJuegoRequest(Proyecto.ServiceReference1.SetDatosJuegoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDatosJuegoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pusuario1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pusuario2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pnivel1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pnivel2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pnivel3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pnivel4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int ptamx;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int ptamy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int ptipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ptiempo;
        
        public SetDatosJuegoRequestBody() {
        }
        
        public SetDatosJuegoRequestBody(string pusuario1, string pusuario2, int pnivel1, int pnivel2, int pnivel3, int pnivel4, int ptamx, int ptamy, int ptipo, string ptiempo) {
            this.pusuario1 = pusuario1;
            this.pusuario2 = pusuario2;
            this.pnivel1 = pnivel1;
            this.pnivel2 = pnivel2;
            this.pnivel3 = pnivel3;
            this.pnivel4 = pnivel4;
            this.ptamx = ptamx;
            this.ptamy = ptamy;
            this.ptipo = ptipo;
            this.ptiempo = ptiempo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDatosJuegoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDatosJuegoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.SetDatosJuegoResponseBody Body;
        
        public SetDatosJuegoResponse() {
        }
        
        public SetDatosJuegoResponse(Proyecto.ServiceReference1.SetDatosJuegoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetDatosJuegoResponseBody {
        
        public SetDatosJuegoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsuario1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsuario1", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.GetUsuario1RequestBody Body;
        
        public GetUsuario1Request() {
        }
        
        public GetUsuario1Request(Proyecto.ServiceReference1.GetUsuario1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsuario1RequestBody {
        
        public GetUsuario1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsuario1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsuario1Response", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.GetUsuario1ResponseBody Body;
        
        public GetUsuario1Response() {
        }
        
        public GetUsuario1Response(Proyecto.ServiceReference1.GetUsuario1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsuario1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUsuario1Result;
        
        public GetUsuario1ResponseBody() {
        }
        
        public GetUsuario1ResponseBody(string GetUsuario1Result) {
            this.GetUsuario1Result = GetUsuario1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsuario2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsuario2", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.GetUsuario2RequestBody Body;
        
        public GetUsuario2Request() {
        }
        
        public GetUsuario2Request(Proyecto.ServiceReference1.GetUsuario2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsuario2RequestBody {
        
        public GetUsuario2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsuario2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsuario2Response", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.GetUsuario2ResponseBody Body;
        
        public GetUsuario2Response() {
        }
        
        public GetUsuario2Response(Proyecto.ServiceReference1.GetUsuario2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsuario2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUsuario2Result;
        
        public GetUsuario2ResponseBody() {
        }
        
        public GetUsuario2ResponseBody(string GetUsuario2Result) {
            this.GetUsuario2Result = GetUsuario2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTiempoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTiempo", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.GetTiempoRequestBody Body;
        
        public GetTiempoRequest() {
        }
        
        public GetTiempoRequest(Proyecto.ServiceReference1.GetTiempoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTiempoRequestBody {
        
        public GetTiempoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTiempoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTiempoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.GetTiempoResponseBody Body;
        
        public GetTiempoResponse() {
        }
        
        public GetTiempoResponse(Proyecto.ServiceReference1.GetTiempoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTiempoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTiempoResult;
        
        public GetTiempoResponseBody() {
        }
        
        public GetTiempoResponseBody(string GetTiempoResult) {
            this.GetTiempoResult = GetTiempoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarJuegoActualRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargarJuegoActual", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.CargarJuegoActualRequestBody Body;
        
        public CargarJuegoActualRequest() {
        }
        
        public CargarJuegoActualRequest(Proyecto.ServiceReference1.CargarJuegoActualRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargarJuegoActualRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ruta;
        
        public CargarJuegoActualRequestBody() {
        }
        
        public CargarJuegoActualRequestBody(string ruta) {
            this.ruta = ruta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarJuegoActualResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargarJuegoActualResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.CargarJuegoActualResponseBody Body;
        
        public CargarJuegoActualResponse() {
        }
        
        public CargarJuegoActualResponse(Proyecto.ServiceReference1.CargarJuegoActualResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargarJuegoActualResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CargarJuegoActualResult;
        
        public CargarJuegoActualResponseBody() {
        }
        
        public CargarJuegoActualResponseBody(string CargarJuegoActualResult) {
            this.CargarJuegoActualResult = CargarJuegoActualResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarJuegosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargarJuegos", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.CargarJuegosRequestBody Body;
        
        public CargarJuegosRequest() {
        }
        
        public CargarJuegosRequest(Proyecto.ServiceReference1.CargarJuegosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargarJuegosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ruta;
        
        public CargarJuegosRequestBody() {
        }
        
        public CargarJuegosRequestBody(string ruta) {
            this.ruta = ruta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarJuegosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargarJuegosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.CargarJuegosResponseBody Body;
        
        public CargarJuegosResponse() {
        }
        
        public CargarJuegosResponse(Proyecto.ServiceReference1.CargarJuegosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CargarJuegosResponseBody {
        
        public CargarJuegosResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarTableroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargarTablero", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.CargarTableroRequestBody Body;
        
        public CargarTableroRequest() {
        }
        
        public CargarTableroRequest(Proyecto.ServiceReference1.CargarTableroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargarTableroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ruta;
        
        public CargarTableroRequestBody() {
        }
        
        public CargarTableroRequestBody(string ruta) {
            this.ruta = ruta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarTableroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargarTableroResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.CargarTableroResponseBody Body;
        
        public CargarTableroResponse() {
        }
        
        public CargarTableroResponse(Proyecto.ServiceReference1.CargarTableroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CargarTableroResponseBody {
        
        public CargarTableroResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.CargarUsuariosRequestBody Body;
        
        public CargarUsuariosRequest() {
        }
        
        public CargarUsuariosRequest(Proyecto.ServiceReference1.CargarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargarUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ruta;
        
        public CargarUsuariosRequestBody() {
        }
        
        public CargarUsuariosRequestBody(string ruta) {
            this.ruta = ruta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.CargarUsuariosResponseBody Body;
        
        public CargarUsuariosResponse() {
        }
        
        public CargarUsuariosResponse(Proyecto.ServiceReference1.CargarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CargarUsuariosResult;
        
        public CargarUsuariosResponseBody() {
        }
        
        public CargarUsuariosResponseBody(bool CargarUsuariosResult) {
            this.CargarUsuariosResult = CargarUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.BuscarUsuarioRequestBody Body;
        
        public BuscarUsuarioRequest() {
        }
        
        public BuscarUsuarioRequest(Proyecto.ServiceReference1.BuscarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pnickname;
        
        public BuscarUsuarioRequestBody() {
        }
        
        public BuscarUsuarioRequestBody(string pnickname) {
            this.pnickname = pnickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.BuscarUsuarioResponseBody Body;
        
        public BuscarUsuarioResponse() {
        }
        
        public BuscarUsuarioResponse(Proyecto.ServiceReference1.BuscarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool BuscarUsuarioResult;
        
        public BuscarUsuarioResponseBody() {
        }
        
        public BuscarUsuarioResponseBody(bool BuscarUsuarioResult) {
            this.BuscarUsuarioResult = BuscarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LlamadaagraficarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Llamadaagraficar", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.LlamadaagraficarRequestBody Body;
        
        public LlamadaagraficarRequest() {
        }
        
        public LlamadaagraficarRequest(Proyecto.ServiceReference1.LlamadaagraficarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LlamadaagraficarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ruta;
        
        public LlamadaagraficarRequestBody() {
        }
        
        public LlamadaagraficarRequestBody(string tipo, string ruta) {
            this.tipo = tipo;
            this.ruta = ruta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LlamadaagraficarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LlamadaagraficarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.LlamadaagraficarResponseBody Body;
        
        public LlamadaagraficarResponse() {
        }
        
        public LlamadaagraficarResponse(Proyecto.ServiceReference1.LlamadaagraficarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LlamadaagraficarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LlamadaagraficarResult;
        
        public LlamadaagraficarResponseBody() {
        }
        
        public LlamadaagraficarResponseBody(bool LlamadaagraficarResult) {
            this.LlamadaagraficarResult = LlamadaagraficarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverusuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Devolverusuario", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverusuarioRequestBody Body;
        
        public DevolverusuarioRequest() {
        }
        
        public DevolverusuarioRequest(Proyecto.ServiceReference1.DevolverusuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverusuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pnickname;
        
        public DevolverusuarioRequestBody() {
        }
        
        public DevolverusuarioRequestBody(string pnickname) {
            this.pnickname = pnickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverusuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverusuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverusuarioResponseBody Body;
        
        public DevolverusuarioResponse() {
        }
        
        public DevolverusuarioResponse(Proyecto.ServiceReference1.DevolverusuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverusuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DevolverusuarioResult;
        
        public DevolverusuarioResponseBody() {
        }
        
        public DevolverusuarioResponseBody(string DevolverusuarioResult) {
            this.DevolverusuarioResult = DevolverusuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.ModificarUsuariosRequestBody Body;
        
        public ModificarUsuariosRequest() {
        }
        
        public ModificarUsuariosRequest(Proyecto.ServiceReference1.ModificarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pnickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string correo;
        
        public ModificarUsuariosRequestBody() {
        }
        
        public ModificarUsuariosRequestBody(string pnickname, string password, string correo) {
            this.pnickname = pnickname;
            this.password = password;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.ModificarUsuariosResponseBody Body;
        
        public ModificarUsuariosResponse() {
        }
        
        public ModificarUsuariosResponse(Proyecto.ServiceReference1.ModificarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificarUsuariosResponseBody {
        
        public ModificarUsuariosResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarNicknameUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarNicknameUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.ModificarNicknameUsuariosRequestBody Body;
        
        public ModificarNicknameUsuariosRequest() {
        }
        
        public ModificarNicknameUsuariosRequest(Proyecto.ServiceReference1.ModificarNicknameUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarNicknameUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pnicknameantiguo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pnicknamenuevo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string correo;
        
        public ModificarNicknameUsuariosRequestBody() {
        }
        
        public ModificarNicknameUsuariosRequestBody(string pnicknameantiguo, string pnicknamenuevo, string password, string correo) {
            this.pnicknameantiguo = pnicknameantiguo;
            this.pnicknamenuevo = pnicknamenuevo;
            this.password = password;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarNicknameUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarNicknameUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.ModificarNicknameUsuariosResponseBody Body;
        
        public ModificarNicknameUsuariosResponse() {
        }
        
        public ModificarNicknameUsuariosResponse(Proyecto.ServiceReference1.ModificarNicknameUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarNicknameUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ModificarNicknameUsuariosResult;
        
        public ModificarNicknameUsuariosResponseBody() {
        }
        
        public ModificarNicknameUsuariosResponseBody(bool ModificarNicknameUsuariosResult) {
            this.ModificarNicknameUsuariosResult = ModificarNicknameUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.EliminarUsuariosRequestBody Body;
        
        public EliminarUsuariosRequest() {
        }
        
        public EliminarUsuariosRequest(Proyecto.ServiceReference1.EliminarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pnickname;
        
        public EliminarUsuariosRequestBody() {
        }
        
        public EliminarUsuariosRequestBody(string pnickname) {
            this.pnickname = pnickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.EliminarUsuariosResponseBody Body;
        
        public EliminarUsuariosResponse() {
        }
        
        public EliminarUsuariosResponse(Proyecto.ServiceReference1.EliminarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EliminarUsuariosResult;
        
        public EliminarUsuariosResponseBody() {
        }
        
        public EliminarUsuariosResponseBody(bool EliminarUsuariosResult) {
            this.EliminarUsuariosResult = EliminarUsuariosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProyectoSoapChannel : Proyecto.ServiceReference1.WebServiceProyectoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProyectoSoapClient : System.ServiceModel.ClientBase<Proyecto.ServiceReference1.WebServiceProyectoSoap>, Proyecto.ServiceReference1.WebServiceProyectoSoap {
        
        public WebServiceProyectoSoapClient() {
        }
        
        public WebServiceProyectoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProyectoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProyectoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProyectoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void IniciarArbol() {
            base.Channel.IniciarArbol();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.HelloWorldResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.HelloWorld(Proyecto.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Proyecto.ServiceReference1.HelloWorldRequest inValue = new Proyecto.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Proyecto.ServiceReference1.HelloWorldRequestBody();
            Proyecto.ServiceReference1.HelloWorldResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.SetDatosJuegoResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.SetDatosJuego(Proyecto.ServiceReference1.SetDatosJuegoRequest request) {
            return base.Channel.SetDatosJuego(request);
        }
        
        public void SetDatosJuego(string pusuario1, string pusuario2, int pnivel1, int pnivel2, int pnivel3, int pnivel4, int ptamx, int ptamy, int ptipo, string ptiempo) {
            Proyecto.ServiceReference1.SetDatosJuegoRequest inValue = new Proyecto.ServiceReference1.SetDatosJuegoRequest();
            inValue.Body = new Proyecto.ServiceReference1.SetDatosJuegoRequestBody();
            inValue.Body.pusuario1 = pusuario1;
            inValue.Body.pusuario2 = pusuario2;
            inValue.Body.pnivel1 = pnivel1;
            inValue.Body.pnivel2 = pnivel2;
            inValue.Body.pnivel3 = pnivel3;
            inValue.Body.pnivel4 = pnivel4;
            inValue.Body.ptamx = ptamx;
            inValue.Body.ptamy = ptamy;
            inValue.Body.ptipo = ptipo;
            inValue.Body.ptiempo = ptiempo;
            Proyecto.ServiceReference1.SetDatosJuegoResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).SetDatosJuego(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.GetUsuario1Response Proyecto.ServiceReference1.WebServiceProyectoSoap.GetUsuario1(Proyecto.ServiceReference1.GetUsuario1Request request) {
            return base.Channel.GetUsuario1(request);
        }
        
        public string GetUsuario1() {
            Proyecto.ServiceReference1.GetUsuario1Request inValue = new Proyecto.ServiceReference1.GetUsuario1Request();
            inValue.Body = new Proyecto.ServiceReference1.GetUsuario1RequestBody();
            Proyecto.ServiceReference1.GetUsuario1Response retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).GetUsuario1(inValue);
            return retVal.Body.GetUsuario1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.GetUsuario2Response Proyecto.ServiceReference1.WebServiceProyectoSoap.GetUsuario2(Proyecto.ServiceReference1.GetUsuario2Request request) {
            return base.Channel.GetUsuario2(request);
        }
        
        public string GetUsuario2() {
            Proyecto.ServiceReference1.GetUsuario2Request inValue = new Proyecto.ServiceReference1.GetUsuario2Request();
            inValue.Body = new Proyecto.ServiceReference1.GetUsuario2RequestBody();
            Proyecto.ServiceReference1.GetUsuario2Response retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).GetUsuario2(inValue);
            return retVal.Body.GetUsuario2Result;
        }
        
        public int GetNumeroNivel1() {
            return base.Channel.GetNumeroNivel1();
        }
        
        public int GetNumeroNivel2() {
            return base.Channel.GetNumeroNivel2();
        }
        
        public int GetNumeroNivel3() {
            return base.Channel.GetNumeroNivel3();
        }
        
        public int GetNumeroNivel4() {
            return base.Channel.GetNumeroNivel4();
        }
        
        public int GetTamX() {
            return base.Channel.GetTamX();
        }
        
        public int GetTamY() {
            return base.Channel.GetTamY();
        }
        
        public int GetTipoJuego() {
            return base.Channel.GetTipoJuego();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.GetTiempoResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.GetTiempo(Proyecto.ServiceReference1.GetTiempoRequest request) {
            return base.Channel.GetTiempo(request);
        }
        
        public string GetTiempo() {
            Proyecto.ServiceReference1.GetTiempoRequest inValue = new Proyecto.ServiceReference1.GetTiempoRequest();
            inValue.Body = new Proyecto.ServiceReference1.GetTiempoRequestBody();
            Proyecto.ServiceReference1.GetTiempoResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).GetTiempo(inValue);
            return retVal.Body.GetTiempoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.CargarJuegoActualResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.CargarJuegoActual(Proyecto.ServiceReference1.CargarJuegoActualRequest request) {
            return base.Channel.CargarJuegoActual(request);
        }
        
        public string CargarJuegoActual(string ruta) {
            Proyecto.ServiceReference1.CargarJuegoActualRequest inValue = new Proyecto.ServiceReference1.CargarJuegoActualRequest();
            inValue.Body = new Proyecto.ServiceReference1.CargarJuegoActualRequestBody();
            inValue.Body.ruta = ruta;
            Proyecto.ServiceReference1.CargarJuegoActualResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).CargarJuegoActual(inValue);
            return retVal.Body.CargarJuegoActualResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.CargarJuegosResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.CargarJuegos(Proyecto.ServiceReference1.CargarJuegosRequest request) {
            return base.Channel.CargarJuegos(request);
        }
        
        public void CargarJuegos(string ruta) {
            Proyecto.ServiceReference1.CargarJuegosRequest inValue = new Proyecto.ServiceReference1.CargarJuegosRequest();
            inValue.Body = new Proyecto.ServiceReference1.CargarJuegosRequestBody();
            inValue.Body.ruta = ruta;
            Proyecto.ServiceReference1.CargarJuegosResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).CargarJuegos(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.CargarTableroResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.CargarTablero(Proyecto.ServiceReference1.CargarTableroRequest request) {
            return base.Channel.CargarTablero(request);
        }
        
        public void CargarTablero(string ruta) {
            Proyecto.ServiceReference1.CargarTableroRequest inValue = new Proyecto.ServiceReference1.CargarTableroRequest();
            inValue.Body = new Proyecto.ServiceReference1.CargarTableroRequestBody();
            inValue.Body.ruta = ruta;
            Proyecto.ServiceReference1.CargarTableroResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).CargarTablero(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.CargarUsuariosResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.CargarUsuarios(Proyecto.ServiceReference1.CargarUsuariosRequest request) {
            return base.Channel.CargarUsuarios(request);
        }
        
        public bool CargarUsuarios(string ruta) {
            Proyecto.ServiceReference1.CargarUsuariosRequest inValue = new Proyecto.ServiceReference1.CargarUsuariosRequest();
            inValue.Body = new Proyecto.ServiceReference1.CargarUsuariosRequestBody();
            inValue.Body.ruta = ruta;
            Proyecto.ServiceReference1.CargarUsuariosResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).CargarUsuarios(inValue);
            return retVal.Body.CargarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.BuscarUsuarioResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.BuscarUsuario(Proyecto.ServiceReference1.BuscarUsuarioRequest request) {
            return base.Channel.BuscarUsuario(request);
        }
        
        public bool BuscarUsuario(string pnickname) {
            Proyecto.ServiceReference1.BuscarUsuarioRequest inValue = new Proyecto.ServiceReference1.BuscarUsuarioRequest();
            inValue.Body = new Proyecto.ServiceReference1.BuscarUsuarioRequestBody();
            inValue.Body.pnickname = pnickname;
            Proyecto.ServiceReference1.BuscarUsuarioResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).BuscarUsuario(inValue);
            return retVal.Body.BuscarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.LlamadaagraficarResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.Llamadaagraficar(Proyecto.ServiceReference1.LlamadaagraficarRequest request) {
            return base.Channel.Llamadaagraficar(request);
        }
        
        public bool Llamadaagraficar(string tipo, string ruta) {
            Proyecto.ServiceReference1.LlamadaagraficarRequest inValue = new Proyecto.ServiceReference1.LlamadaagraficarRequest();
            inValue.Body = new Proyecto.ServiceReference1.LlamadaagraficarRequestBody();
            inValue.Body.tipo = tipo;
            inValue.Body.ruta = ruta;
            Proyecto.ServiceReference1.LlamadaagraficarResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).Llamadaagraficar(inValue);
            return retVal.Body.LlamadaagraficarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.DevolverusuarioResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.Devolverusuario(Proyecto.ServiceReference1.DevolverusuarioRequest request) {
            return base.Channel.Devolverusuario(request);
        }
        
        public string Devolverusuario(string pnickname) {
            Proyecto.ServiceReference1.DevolverusuarioRequest inValue = new Proyecto.ServiceReference1.DevolverusuarioRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverusuarioRequestBody();
            inValue.Body.pnickname = pnickname;
            Proyecto.ServiceReference1.DevolverusuarioResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).Devolverusuario(inValue);
            return retVal.Body.DevolverusuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.ModificarUsuariosResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.ModificarUsuarios(Proyecto.ServiceReference1.ModificarUsuariosRequest request) {
            return base.Channel.ModificarUsuarios(request);
        }
        
        public void ModificarUsuarios(string pnickname, string password, string correo) {
            Proyecto.ServiceReference1.ModificarUsuariosRequest inValue = new Proyecto.ServiceReference1.ModificarUsuariosRequest();
            inValue.Body = new Proyecto.ServiceReference1.ModificarUsuariosRequestBody();
            inValue.Body.pnickname = pnickname;
            inValue.Body.password = password;
            inValue.Body.correo = correo;
            Proyecto.ServiceReference1.ModificarUsuariosResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).ModificarUsuarios(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.ModificarNicknameUsuariosResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.ModificarNicknameUsuarios(Proyecto.ServiceReference1.ModificarNicknameUsuariosRequest request) {
            return base.Channel.ModificarNicknameUsuarios(request);
        }
        
        public bool ModificarNicknameUsuarios(string pnicknameantiguo, string pnicknamenuevo, string password, string correo) {
            Proyecto.ServiceReference1.ModificarNicknameUsuariosRequest inValue = new Proyecto.ServiceReference1.ModificarNicknameUsuariosRequest();
            inValue.Body = new Proyecto.ServiceReference1.ModificarNicknameUsuariosRequestBody();
            inValue.Body.pnicknameantiguo = pnicknameantiguo;
            inValue.Body.pnicknamenuevo = pnicknamenuevo;
            inValue.Body.password = password;
            inValue.Body.correo = correo;
            Proyecto.ServiceReference1.ModificarNicknameUsuariosResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).ModificarNicknameUsuarios(inValue);
            return retVal.Body.ModificarNicknameUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.EliminarUsuariosResponse Proyecto.ServiceReference1.WebServiceProyectoSoap.EliminarUsuarios(Proyecto.ServiceReference1.EliminarUsuariosRequest request) {
            return base.Channel.EliminarUsuarios(request);
        }
        
        public bool EliminarUsuarios(string pnickname) {
            Proyecto.ServiceReference1.EliminarUsuariosRequest inValue = new Proyecto.ServiceReference1.EliminarUsuariosRequest();
            inValue.Body = new Proyecto.ServiceReference1.EliminarUsuariosRequestBody();
            inValue.Body.pnickname = pnickname;
            Proyecto.ServiceReference1.EliminarUsuariosResponse retVal = ((Proyecto.ServiceReference1.WebServiceProyectoSoap)(this)).EliminarUsuarios(inValue);
            return retVal.Body.EliminarUsuariosResult;
        }
    }
}
